# To create the conda environment:
# $ conda env create -f environment.yml
#
# To update the conda environment:
# $ conda env update -f environment.yml
#
# To register the conda environment in Jupyter:
# $ conda activate cait
# $ python -m ipykernel install --user --name cait

name: cait
channels:
- defaults
- conda-forge
dependencies:
- jupyter>=1.0.0
- matplotlib>=3.1.1
- python==3.7.2
- pytest>=3.6.4
- pandas>=0.24.2
- wordcloud>=1.5.0
- geopy>=1.21.0
- pip:
  - black>=18.6b4
  - papermill>=0.15.0
  - pre-commit>=1.14.4
  - flake8
  - lxml>=4.3.2
  - html5lib
  - bs4
  - dateparser
  - pillow
